// <auto-generated />
using System;
using AudiobookLibrary.Core.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AudiobookLibrary.Core.Migrations
{
    [DbContext(typeof(AudioLibraryContext))]
    [Migration("20190401013652_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("AudiobookLibrary.Core.Library.Domain.AudiobookFile", b =>
                {
                    b.Property<int>("AudiobookFileId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Album");

                    b.Property<string>("Author");

                    b.Property<int?>("Disc");

                    b.Property<string>("Filename");

                    b.Property<string>("Image");

                    b.Property<string>("Title");

                    b.Property<int?>("Track");

                    b.HasKey("AudiobookFileId");

                    b.ToTable("AudiobookFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
